# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kobis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boxoffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxofficeType', models.CharField(max_length=20)),
                ('showRange', models.CharField(max_length=20)),
                ('yearWeekTime', models.CharField(max_length=10)),
                ('rnum', models.CharField(max_length=10)),
                ('rank', models.CharField(max_length=10)),
                ('rankInten', models.CharField(max_length=10)),
                ('rankOldAndNew', models.CharField(max_length=10)),
                ('salesAmt', models.CharField(max_length=20)),
                ('salesShare', models.CharField(max_length=10)),
                ('salesInten', models.CharField(max_length=20)),
                ('salesChange', models.CharField(max_length=10)),
                ('salesAcc', models.CharField(max_length=20)),
                ('audiCnt', models.CharField(max_length=10)),
                ('audiInten', models.CharField(max_length=10)),
                ('audiChange', models.CharField(max_length=10)),
                ('audiAcc', models.CharField(max_length=20)),
                ('scrnCnt', models.CharField(max_length=10)),
                ('showCnt', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyCd', models.CharField(max_length=10)),
                ('companyNm', models.CharField(max_length=50)),
                ('companyNmEn', models.CharField(max_length=50)),
                ('companyPartNames', models.CharField(max_length=30)),
                ('ceoNm', models.CharField(max_length=20)),
                ('filmoNames', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts', models.TextField()),
                ('filmos', models.TextField()),
                ('ceoNm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CompanyDetails_ceoNm', to='kobis.Companies')),
                ('companyCd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CompanyDetails_companyCd', to='kobis.Companies')),
                ('companyNm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CompanyDetails_companyNm', to='kobis.Companies')),
                ('companyNmEn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CompanyDetails_companyNmEn', to='kobis.Companies')),
            ],
        ),
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieNmOg', models.TextField()),
                ('showTm', models.CharField(max_length=10)),
                ('nations', models.TextField()),
                ('genre', models.TextField()),
                ('directors', models.TextField()),
                ('actors', models.TextField()),
                ('showTypes', models.TextField()),
                ('audits', models.TextField()),
                ('companys', models.TextField()),
                ('staffs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieCd', models.CharField(max_length=10)),
                ('movieNm', models.CharField(max_length=50)),
                ('movieNmEn', models.CharField(max_length=50)),
                ('prdtYear', models.CharField(max_length=10)),
                ('openDt', models.CharField(max_length=10)),
                ('typeNm', models.CharField(max_length=10)),
                ('prdtStatNm', models.CharField(max_length=10)),
                ('nationAlt', models.CharField(max_length=30)),
                ('genreAlt', models.CharField(max_length=30)),
                ('repNationNm', models.CharField(max_length=10)),
                ('repGenreNm', models.CharField(max_length=10)),
                ('directors', models.CharField(max_length=50)),
                ('companys', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peopleCd', models.CharField(max_length=10)),
                ('peopleNm', models.CharField(max_length=10)),
                ('peopleNmEn', models.CharField(max_length=30)),
                ('repRoleNm', models.CharField(max_length=10)),
                ('filmoNames', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=10)),
                ('filmos', models.TextField()),
                ('homepages', models.CharField(max_length=50)),
                ('peopleCd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonDetails_peopleCd', to='kobis.People')),
                ('peopleNm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonDetails_peopleNm', to='kobis.People')),
                ('peopleNmEn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonDetails_peopleNmEn', to='kobis.People')),
                ('repRoleNm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonDetails_repRoleNm', to='kobis.People')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='movieCd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MovieDetails_movieCd', to='kobis.Movies'),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='movieNm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MovieDetails_movieNm', to='kobis.Movies'),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='movieNmEn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MovieDetails_movieNmEn', to='kobis.Movies'),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='openDt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MovieDetails_openDt', to='kobis.Movies'),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='prdtStatNm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MovieDetails_prdtStatNm', to='kobis.Movies'),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='prdtYear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MovieDetails_prdtYear', to='kobis.Movies'),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='typeNm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MovieDetails_typeNm', to='kobis.Movies'),
        ),
        migrations.AddField(
            model_name='boxoffice',
            name='movieCd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Boxoffice_movieCd', to='kobis.Movies'),
        ),
        migrations.AddField(
            model_name='boxoffice',
            name='movieNm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Boxoffice_movieNm', to='kobis.Movies'),
        ),
        migrations.AddField(
            model_name='boxoffice',
            name='openDt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Boxoffice_openDt', to='kobis.Movies'),
        ),
    ]
