# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobis', '0002_auto_20170830_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='companys',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='directors',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movieNm',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movieNmEn',
            field=models.CharField(max_length=100),
        ),
    ]
