# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobis', '0004_auto_20170831_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxoffice',
            name='showRange',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='companyCd',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='peopleCd',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
