# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobis', '0005_auto_20170907_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='companys',
        ),
        migrations.AddField(
            model_name='movies',
            name='companys',
            field=models.ManyToManyField(related_name='Movies_company', to='kobis.Companies'),
        ),
        migrations.RemoveField(
            model_name='movies',
            name='directors',
        ),
        migrations.AddField(
            model_name='movies',
            name='directors',
            field=models.ManyToManyField(related_name='Movies_director', to='kobis.People'),
        ),
    ]
